services:
  _defaults:
    autowire: true
    autoconfigure: false

  App\RegionalRepresentatives\RegionalRepresentativeRepository:

  App\RegionalRepresentatives\RegionalRepresentativeController:
    tags: ['controller.service_arguments']