version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: docker-compose/Dockerfile
    image: travellist
    container_name: dos_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - storage:/var/www/storage
      - storage:/var/www/public/storage
      - geoip_data:/geoip_data:ro
    networks:
      - doc
  database:
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - ./docker-compose/dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
<<<<<<< HEAD
    - 5482:5432
=======
      - 5482:5432
>>>>>>> main
    networks:
      - doc
  adminer:
    image: adminer
    restart: always
    ports:
      - 2232:8080
    volumes:
      - ./docker-compose/adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - doc

  nginx:
    image: nginx:latest
    container_name: dos_nginx
    restart: unless-stopped
    ports:
      - 8020:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - storage:/var/www/storage
      - storage:/var/www/public/storage
    networks:
      - doc
  imgproxy:
    image: darthsim/imgproxy:v2.10
    ports:
      - 8001:8080
    environment:
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/mnt/data
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ENFORCE_WEBP=true
    volumes:
      - storage:/mnt/data/storage
    networks:
      - doc
  geoip_updater:
    image: crazymax/geoip-updater:latest
    environment:
      - TZ=Asia/Almaty
      - EDITION_IDS=GeoLite2-City
      - LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - DOWNLOAD_PATH=/data
      - SCHEDULE=0 0 * * 0
    volumes:
      - geoip_data:/data
  gotenberg:
    image: thecodingmachine/gotenberg:6
    container_name: gotenberg
    ports:
      - 3000:3000
    networks:
      - doc
volumes:
  storage: { }
  geoip_data: { }
networks:
  doc:
    driver: bridge
