services:
  _defaults:
    autowire: true
    autoconfigure: false

  App\Awards\IssueAwardForAddedObjects:
    tags: ['domain_events.listener']

  App\Awards\AwardRepository:

  App\Awards\AwardsAdminController:
    tags: ['controller.service_arguments']